version: '2'

portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock --no-auth
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: